In [1]:
import pandas as pd

In [17]:
audio = pd.read_csv('../datasets/audio_sarcasm_dataset.csv')
audio.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'spectral_centroid', 'spectral_bandwidth', 'pitch', 'energy',
       'loudness', 'AUDIO_1', 'AUDIO_2', 'AUDIO_3', 'AUDIO_4', 'AUDIO_5',
       'AUDIO_6', 'AUDIO_7', 'AUDIO_8'],
      dtype='object')

In [3]:
# Assuming df is your DataFrame
audio.rename(columns={
    'AUDIO_1': 'PCA_MFCC_1',
    'AUDIO_2': 'PCA_MFCC_2',
    'AUDIO_3': 'PCA_MFCC_3',
    'AUDIO_4': 'PCA_MFCC_4',
    'AUDIO_5': 'PCA_MFCC_5',
    'AUDIO_6': 'PCA_MFCC_6',
    'AUDIO_7': 'PCA_MFCC_7',
    'AUDIO_8': 'PCA_MFCC_8'
}, inplace=True)

In [4]:
audio

,Unnamed: 0,sarcasm_label,emotion_label,sentiment_label,id,spectral_centroid,spectral_bandwidth,pitch,energy,loudness,PCA_MFCC_1,PCA_MFCC_2,PCA_MFCC_3,PCA_MFCC_4,PCA_MFCC_5,PCA_MFCC_6,PCA_MFCC_7,PCA_MFCC_8
0,0,0,anger,0,1,3194.061155,2498.073258,1724.7588,0.000169,0.009737,-2.276627,1.194254,1.073762,-0.120506,-0.308371,0.027054,-0.521969,-1.144353
1,1,0,anger,0,2,3207.430827,2460.578687,1596.3215,0.000481,0.017747,-0.920419,-0.245156,1.557069,-0.234828,0.540239,1.073943,0.077584,1.199006
2,2,0,anger,0,3,3189.165736,2348.431343,2021.3490,0.000165,0.009494,-1.511857,-0.118752,0.132647,-0.888176,0.340909,-1.137311,0.961322,1.532151
3,3,0,anger,0,4,4078.493479,3491.345131,1616.6838,0.000181,0.008689,-1.032136,1.556911,0.385882,-0.252339,-0.164264,-0.412079,-0.039664,-0.533009
4,4,0,anger,0,5,3678.133007,2459.192276,1724.6781,0.001107,0.024616,0.139397,-0.984472,0.358380,0.581564,-0.502099,-0.111040,0.787407,0.286733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,419,0,surprise,0,420,2402.865342,2090.375822,1649.7700,0.000435,0.017317,-1.219419,0.458677,2.047222,0.538345,1.131656,-0.402536,-0.563440,0.952709
255,421,0,surprise,0,422,4141.032863,3838.504821,1244.7019,0.000086,0.005430,-0.195316,-0.250842,-0.458744,-0.920555,-0.709591,-0.709534,-0.109214,-0.370972
256,422,0,surprise,0,423,3080.676592,3591.771581,1928.5706,0.000154,0.008661,2.020319,2.749040,-0.155967,-0.044834,0.379603,0.893045,-0.124065,1.150491
257,425,0,surprise,0,426,5777.586640,4555.686200,1681.1293,0.000048,0.003806,-1.857867,1.587987,-0.524588,-0.655474,-1.968691,0.052819,-1.107251,0.223600
258,427,0,surprise,0,428,2472.252426,2386.249516,1754.9476,0.000246,0.012379,-2.124620,-0.969605,2.702946,-0.300067,0.464363,0.705530,-0.208636,0.481005

In [5]:
audio = audio.drop(columns = ['energy', 'loudness'])

In [6]:
pd.read_csv('../datasets/text_sarcasm_dataset.csv').columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'sentence_level_similarity_emotion', 'sentence_level_similarity_word',
       'exclamation', 'TEXT_1', 'TEXT_2', 'TEXT_3', 'TEXT_4', 'TEXT_5',
       'TEXT_6', 'TEXT_7', 'TEXT_8', 'TEXT_9', 'TEXT_10', 'TEXT_11', 'TEXT_12',
       'TEXT_13', 'TEXT_14', 'TEXT_15', 'TEXT_16', 'TEXT_17', 'TEXT_18',
       'TEXT_19', 'TEXT_20', 'TEXT_21', 'TEXT_22', 'TEXT_23', 'TEXT_24',
       'TEXT_25', 'TEXT_26', 'TEXT_27', 'TEXT_28', 'TEXT_29', 'TEXT_30',
       'TEXT_31', 'TEXT_32', 'TEXT_33', 'TEXT_34', 'TEXT_35', 'TEXT_36',
       'TEXT_37', 'TEXT_38', 'TEXT_39', 'TEXT_40', 'TEXT_41', 'TEXT_42',
       'TEXT_43', 'TEXT_44', 'TEXT_45', 'TEXT_46', 'TEXT_47', 'TEXT_48',
       'TEXT_49', 'TEXT_50'],
      dtype='object')

In [7]:
text = pd.read_csv('../datasets/text_sarcasm_dataset.csv')

# Assuming df is your DataFrame
text.rename(columns={
    f'TEXT_{i}': f'PCA_W2V_{i}' for i in range(1, 61)  # This creates mappings from TEXT_1 to TEXT_50
}, inplace=True)

text.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'sentence_level_similarity_emotion', 'sentence_level_similarity_word',
       'exclamation', 'PCA_W2V_1', 'PCA_W2V_2', 'PCA_W2V_3', 'PCA_W2V_4',
       'PCA_W2V_5', 'PCA_W2V_6', 'PCA_W2V_7', 'PCA_W2V_8', 'PCA_W2V_9',
       'PCA_W2V_10', 'PCA_W2V_11', 'PCA_W2V_12', 'PCA_W2V_13', 'PCA_W2V_14',
       'PCA_W2V_15', 'PCA_W2V_16', 'PCA_W2V_17', 'PCA_W2V_18', 'PCA_W2V_19',
       'PCA_W2V_20', 'PCA_W2V_21', 'PCA_W2V_22', 'PCA_W2V_23', 'PCA_W2V_24',
       'PCA_W2V_25', 'PCA_W2V_26', 'PCA_W2V_27', 'PCA_W2V_28', 'PCA_W2V_29',
       'PCA_W2V_30', 'PCA_W2V_31', 'PCA_W2V_32', 'PCA_W2V_33', 'PCA_W2V_34',
       'PCA_W2V_35', 'PCA_W2V_36', 'PCA_W2V_37', 'PCA_W2V_38', 'PCA_W2V_39',
       'PCA_W2V_40', 'PCA_W2V_41', 'PCA_W2V_42', 'PCA_W2V_43', 'PCA_W2V_44',
       'PCA_W2V_45', 'PCA_W2V_46', 'PCA_W2V_47', 'PCA_W2V_48', 'PCA_W2V_49',
       'PCA_W2V_50'],
      dtype='object')

In [8]:
text = text[['id', 'PCA_W2V_1', 'PCA_W2V_2', 'PCA_W2V_3', 'PCA_W2V_4',
       'PCA_W2V_5', 'PCA_W2V_6', 'PCA_W2V_7', 'PCA_W2V_8', 'PCA_W2V_9',
       'PCA_W2V_10', 'PCA_W2V_11', 'PCA_W2V_12', 'PCA_W2V_13', 'PCA_W2V_14',
       'PCA_W2V_15', 'PCA_W2V_16', 'PCA_W2V_17', 'PCA_W2V_18', 'PCA_W2V_19',
       'PCA_W2V_20', 'PCA_W2V_21', 'PCA_W2V_22', 'PCA_W2V_23', 'PCA_W2V_24',
       'PCA_W2V_25', 'PCA_W2V_26', 'PCA_W2V_27', 'PCA_W2V_28', 'PCA_W2V_29',
       'PCA_W2V_30', 'PCA_W2V_31', 'PCA_W2V_32', 'PCA_W2V_33', 'PCA_W2V_34',
       'PCA_W2V_35', 'PCA_W2V_36', 'PCA_W2V_37', 'PCA_W2V_38', 'PCA_W2V_39',
       'PCA_W2V_40', 'PCA_W2V_41', 'PCA_W2V_42', 'PCA_W2V_43', 'PCA_W2V_44',
       'PCA_W2V_45', 'PCA_W2V_46', 'PCA_W2V_47', 'PCA_W2V_48', 'PCA_W2V_49',
       'PCA_W2V_50']]

In [9]:
merged_df = audio.merge(text, on='id', suffixes=('_audio', '_text'))

# Filter out the _text columns that have a corresponding _audio column
for col in merged_df.columns:
    if col.endswith('_text'):
        audio_col = col.replace('_text', '_audio')
        if audio_col in merged_df.columns:
            merged_df.drop(col, axis=1, inplace=True)  # Drop the text column if the audio column exists
        else:
            # Rename back to original if no corresponding audio column exists
            merged_df.rename(columns={col: col.replace('_text', '')}, inplace=True)

# Optionally, rename columns to remove the suffix from audio columns where no overlap occurred
for col in merged_df.columns:
    if col.endswith('_audio'):
        merged_df.rename(columns={col: col.replace('_audio', '')}, inplace=True)

# Now merged_df contains all columns from 'audio' and only non-overlapping columns from 'text'

In [10]:
merged_df.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'spectral_centroid', 'spectral_bandwidth', 'pitch', 'PCA_MFCC_1',
       'PCA_MFCC_2', 'PCA_MFCC_3', 'PCA_MFCC_4', 'PCA_MFCC_5', 'PCA_MFCC_6',
       'PCA_MFCC_7', 'PCA_MFCC_8', 'PCA_W2V_1', 'PCA_W2V_2', 'PCA_W2V_3',
       'PCA_W2V_4', 'PCA_W2V_5', 'PCA_W2V_6', 'PCA_W2V_7', 'PCA_W2V_8',
       'PCA_W2V_9', 'PCA_W2V_10', 'PCA_W2V_11', 'PCA_W2V_12', 'PCA_W2V_13',
       'PCA_W2V_14', 'PCA_W2V_15', 'PCA_W2V_16', 'PCA_W2V_17', 'PCA_W2V_18',
       'PCA_W2V_19', 'PCA_W2V_20', 'PCA_W2V_21', 'PCA_W2V_22', 'PCA_W2V_23',
       'PCA_W2V_24', 'PCA_W2V_25', 'PCA_W2V_26', 'PCA_W2V_27', 'PCA_W2V_28',
       'PCA_W2V_29', 'PCA_W2V_30', 'PCA_W2V_31', 'PCA_W2V_32', 'PCA_W2V_33',
       'PCA_W2V_34', 'PCA_W2V_35', 'PCA_W2V_36', 'PCA_W2V_37', 'PCA_W2V_38',
       'PCA_W2V_39', 'PCA_W2V_40', 'PCA_W2V_41', 'PCA_W2V_42', 'PCA_W2V_43',
       'PCA_W2V_44', 'PCA_W2V_45', 'PCA_W2V_46', 'PCA_W2V_47', 'PCA_W2V_48',
       'PCA_W2V_49', 'PCA_W2V_50'],
      dtype='object')

In [11]:
sum(merged_df.sarcasm_label)

71

In [20]:
merged_df.to_csv('sarcasm_final.csv')

In [16]:
merged_df.drop_duplicates('id')

,Unnamed: 0,sarcasm_label,emotion_label,sentiment_label,id,spectral_centroid,spectral_bandwidth,pitch,PCA_MFCC_1,PCA_MFCC_2,...,PCA_W2V_41,PCA_W2V_42,PCA_W2V_43,PCA_W2V_44,PCA_W2V_45,PCA_W2V_46,PCA_W2V_47,PCA_W2V_48,PCA_W2V_49,PCA_W2V_50
0,0,0,anger,0,1,3194.061155,2498.073258,1724.7588,-2.276627,1.194254,...,-3.528326,5.195582,-2.071413,2.389241,-0.679799,-1.464318,2.688781,1.950308,-1.281537,-0.505422
1,1,0,anger,0,2,3207.430827,2460.578687,1596.3215,-0.920419,-0.245156,...,4.879186,-1.806766,-7.082715,-2.375127,2.932272,-1.903256,7.856745,4.622939,1.243021,2.524237
2,2,0,anger,0,3,3189.165736,2348.431343,2021.3490,-1.511857,-0.118752,...,8.493502,-3.512994,2.752871,-1.689377,3.118805,-0.926467,-0.505093,0.921205,-2.015440,0.257554
3,3,0,anger,0,4,4078.493479,3491.345131,1616.6838,-1.032136,1.556911,...,0.143942,1.922510,1.761534,-0.180522,0.999845,4.713001,0.863674,-0.488971,-1.116376,-2.301616
4,4,0,anger,0,5,3678.133007,2459.192276,1724.6781,0.139397,-0.984472,...,-1.793798,1.769770,0.242620,0.510232,1.445818,2.013260,0.900879,1.465607,0.475343,-2.228691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,419,0,surprise,0,420,2402.865342,2090.375822,1649.7700,-1.219419,0.458677,...,-1.737109,4.056155,0.947543,1.190202,1.446018,2.297449,-1.035243,-0.385022,2.778561,1.791775
255,421,0,surprise,0,422,4141.032863,3838.504821,1244.7019,-0.195316,-0.250842,...,-0.281552,-0.693386,-0.137404,-0.627561,0.753154,-1.652641,0.852713,3.201987,1.966591,3.279186
256,422,0,surprise,0,423,3080.676592,3591.771581,1928.5706,2.020319,2.749040,...,0.133216,-0.857063,-0.324311,1.159971,-1.459785,0.298021,0.313660,4.078432,1.701545,-2.340982
257,425,0,surprise,0,426,5777.586640,4555.686200,1681.1293,-1.857867,1.587987,...,0.924546,1.730823,0.306840,1.716419,0.743047,-2.220859,-2.712793,-0.492945,2.053580,-0.552733
258,427,0,surprise,0,428,2472.252426,2386.249516,1754.9476,-2.124620,-0.969605,...,-0.490707,0.570019,-2.119824,-0.758980,-0.836084,-0.162701,1.185396,-0.860950,-0.592937,1.503745

In [ ]:
merged_df = audio.merge(text, on='id', suffixes=('_audio', '_text'))

# Filter out the _text columns that have a corresponding _audio column
for col in merged_df.columns:
    if col.endswith('_text'):
        audio_col = col.replace('_text', '_audio')
        if audio_col in merged_df.columns:
            merged_df.drop(col, axis=1, inplace=True)  # Drop the text column if the audio column exists
        else:
            # Rename back to original if no corresponding audio column exists
            merged_df.rename(columns={col: col.replace('_text', '')}, inplace=True)

# Optionally, rename columns to remove the suffix from audio columns where no overlap occurred
for col in merged_df.columns:
    if col.endswith('_audio'):
        merged_df.rename(columns={col: col.replace('_audio', '')}, inplace=True)

# Now merged_df contains all columns from 'audio' and only non-overlapping columns from 'text'

In [42]:
merged_df.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'sentence_level_similarity_emotion', 'sentence_level_similarity_word',
       'exclamation', 'PCA_MFCC_1', 'PCA_MFCC_2', 'PCA_MFCC_3', 'PCA_MFCC_4',
       'PCA_MFCC_5', 'PCA_MFCC_6', 'PCA_MFCC_7', 'PCA_MFCC_8', 'PCA_W2V_1',
       'PCA_W2V_2', 'PCA_W2V_3', 'PCA_W2V_4', 'PCA_W2V_5', 'PCA_W2V_6',
       'PCA_W2V_7', 'PCA_W2V_8', 'PCA_W2V_9', 'PCA_W2V_10', 'PCA_W2V_11',
       'PCA_W2V_12', 'PCA_W2V_13', 'PCA_W2V_14', 'PCA_W2V_15', 'PCA_W2V_16',
       'PCA_W2V_17', 'PCA_W2V_18', 'PCA_W2V_19', 'PCA_W2V_20', 'PCA_W2V_21',
       'PCA_W2V_22', 'PCA_W2V_23', 'PCA_W2V_24', 'PCA_W2V_25', 'PCA_W2V_26',
       'PCA_W2V_27', 'PCA_W2V_28', 'PCA_W2V_29', 'PCA_W2V_30', 'PCA_W2V_31',
       'PCA_W2V_32', 'PCA_W2V_33', 'PCA_W2V_34', 'PCA_W2V_35', 'PCA_W2V_36',
       'PCA_W2V_37', 'PCA_W2V_38', 'PCA_W2V_39', 'PCA_W2V_40', 'PCA_W2V_41',
       'PCA_W2V_42', 'PCA_W2V_43', 'PCA_W2V_44', 'PCA_W2V_45', 'PCA_W2V_46',
       'PCA_W2V_47', 'PCA_W2V_48', 'PCA_W2V_49', 'PCA_W2V_50', 'PCA_51',
       'PCA_52', 'PCA_53', 'PCA_54', 'PCA_55', 'PCA_56', 'PCA_57', 'PCA_58',
       'PCA_59', 'PCA_60', 'spectral_centroid', 'spectral_bandwidth', 'pitch'],
      dtype='object')

In [41]:
ref = pd.read_csv('../datasets/sarcasm_final.csv')
set(ref.columns) - set(merged_df.columns)

{'PCA_W2V_51',
 'PCA_W2V_52',
 'PCA_W2V_53',
 'PCA_W2V_54',
 'PCA_W2V_55',
 'PCA_W2V_56',
 'PCA_W2V_57',
 'PCA_W2V_58',
 'PCA_W2V_59',
 'PCA_W2V_60',
 'energy',
 'loudness',
 'mfccs_1',
 'mfccs_10',
 'mfccs_11',
 'mfccs_12',
 'mfccs_13',
 'mfccs_2',
 'mfccs_3',
 'mfccs_4',
 'mfccs_5',
 'mfccs_6',
 'mfccs_7',
 'mfccs_8',
 'mfccs_9'}